# Generated by Django 5.2.3 on 2025-07-18 16:17

import django.db.models.deletion
import utils.tools_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(default=None, max_length=255, verbose_name='Nome')),
                ('contato', models.CharField(default=None, max_length=255, verbose_name='Contato')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('Arquivos', models.FileField(upload_to=utils.tools_utils.cliente_upload_path, verbose_name='Arquivos')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('Usuario', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipe', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('Cargo', models.CharField(choices=[('Vendedor', 'Vendedor'), ('Gerente', 'Gerencia'), ('Supervisor', 'Supervisão'), ('Direção', 'Direção')], default=None, max_length=60)),
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Equipe',
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_venda', models.DateField(default=None, verbose_name='Data de venda')),
                ('Previsao', models.IntegerField(blank=True, null=True, verbose_name='Previsao')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendas', to='posvendasapp.clientes', verbose_name='Cliente')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor', to='posvendasapp.equipe', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Produto', models.CharField(default=None, max_length=255, verbose_name='Produto')),
                ('tipo', models.CharField(choices=[('Contato-diaria', 'Contato-diaria'), ('Contato-Quinzenal', 'Contato-Quinzenal'), ('Solar', 'Armação'), ('Receituario', 'Armação'), ('Multifocal', 'Lente Oftalmica'), ('Visão simples', 'Lente oftalmica')], default=None, max_length=60)),
                ('Valor_venda', models.DecimalField(decimal_places=2, default=None, max_digits=9, verbose_name='Valor de venda')),
                ('valor_produto_sem_desconto', models.DecimalField(decimal_places=2, default=None, max_digits=9, verbose_name='Valor original do produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_vendidos', to='posvendasapp.vendas', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ocorrencia', models.CharField(default=None, max_length=255, verbose_name='Titulo')),
                ('tipo_ocorrencia', models.CharField(choices=[('Troca-compra errada', 'Troca compra Errada'), ('Troca-Garantia', 'Troca-Garantia'), ('Atualização', 'Atualização'), ('Manutenção', 'Manutenção')], default=None, max_length=60)),
                ('data_correncia', models.DateField(auto_now_add=True, verbose_name='Data de correncia')),
                ('ocorrencia', models.TextField(blank=True, default='Descreva a ocorrencia', max_length=5000, null=True, verbose_name='Ocorrencia')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor_ocorrencia', to='posvendasapp.equipe', verbose_name='Vendedor')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_venda', to='posvendasapp.vendas', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
    ]
