# Generated by Django 5.2.3 on 2025-07-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='vendedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor', to='posvendasapp.equipe', verbose_name='Vendedor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produtos',
            name='Valor_venda',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, verbose_name='Valor de venda'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor_produto_sem_desconto',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=9, verbose_name='Valor original do produto'),
        ),
    ]
