# Generated by Django 5.2.3 on 2025-07-18 16:20

import utils.tools_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Arquivos',
            field=models.FileField(blank=True, null=True, upload_to=utils.tools_utils.cliente_upload_path, verbose_name='Arquivos'),
        ),
    ]
