# Generated by Django 5.2.3 on 2025-07-08 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0002_vendas_vendedor_alter_produtos_valor_venda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_ocorrencia', models.CharField(default=None, max_length=255, verbose_name='Titulo')),
                ('tipo_ocorrencia', models.CharField(choices=[('Troca de produto', 'Troca compra Errada'), ('Troca-Garantia', 'Receita Errada'), ('Atualização', 'Atualização'), ('Manutenção', 'Manutenção')], default=None, max_length=60)),
                ('data_correncia', models.DateField(auto_now_add=True, verbose_name='Data de correncia')),
                ('ocorrencia', models.TextField(blank=True, default='Descreva a ocorrencia', max_length=5000, null=True, verbose_name='Ocorrencia')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_venda', to='posvendasapp.vendas', verbose_name='Venda')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vendedor_ocorrencia', to='posvendasapp.equipe', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Ocorrencia',
                'verbose_name_plural': 'Ocorrencias',
            },
        ),
    ]
