# Generated by Django 5.2.3 on 2025-07-30 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0002_alter_clientes_arquivos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='contato',
            new_name='tel_contato',
        ),
        migrations.AddField(
            model_name='clientes',
            name='aniversario',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Data de Aniversario'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email'),
        ),

    ]
