# Generated by Django 5.2.3 on 2025-07-30 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0003_remove_clientes_contato_clientes_aniversario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='sequencia_venda',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, unique=True, verbose_name='Sequencia de venda'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel_contato',
            field=models.CharField(default=None, max_length=255, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='digite somente numeros', regex='^\\d{11}$')], verbose_name='telefone de contato'),
        ),
    ]
