# Generated by Django 5.2.3 on 2025-07-30 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0004_vendas_sequencia_venda_alter_clientes_tel_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='tel_contato',
            field=models.CharField(default=None, max_length=255, validators=[django.core.validators.RegexValidator(code='Numero Invalido', message='digite somente numeros', regex='^\\d{10,11}$')], verbose_name='telefone de contato'),
        ),
    ]
