# Generated by Django 5.2.3 on 2025-07-31 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0005_alter_clientes_tel_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Nome',
            field=models.CharField(default=None, max_length=254, verbose_name='Nome'),
        ),
    ]
