# Generated by Django 5.2.3 on 2025-09-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0009_encrypt_existing_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='aniversario',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='email',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='tel_contato',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='aniversario_encrypted',
            field=models.BinaryField(blank=True, null=True, verbose_name='Aniversário'),
        ),
    ]
