# Generated by Django 5.2.3 on 2025-09-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0010_remove_clientes_aniversario_remove_clientes_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cpf_search',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='email_search',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tel_contato_search',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
