# Generated by Django 5.2.3 on 2025-09-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0011_clientes_cpf_search_clientes_email_search_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='cpf_search',
        ),
        migrations.AddField(
            model_name='clientes',
            name='cpf_hash',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, verbose_name='CPF'),
        ),
    ]
