# Generated by Django 5.2.3 on 2025-09-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0013_populate_cpf_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='email_search',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='tel_contato_search',
        ),
        migrations.AddField(
            model_name='clientes',
            name='aniversario_hash',
            field=models.CharField(blank=True, default=None, editable=False, max_length=64, null=True, verbose_name='Aniversário (hash)'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='email_hash',
            field=models.EmailField(blank=True, default=None, editable=False, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tel_contato_hash',
            field=models.CharField(blank=True, default=None, editable=False, max_length=254, null=True, verbose_name='Telefone'),
        ),
    ]
