# Generated by Django 5.2.3 on 2025-10-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posvendasapp', '0015_populate_hash_fields'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientes',
            constraint=models.UniqueConstraint(fields=('cpf_hash',), name='unique_cpf_hash_constraint'),
        ),
    ]
